### ISSUE TITLE
3.0.8 seems to introduce a module level dependency on document

### ISSUE THREAD

**Issue by radiosilence** [micromark/micromark#100]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.8

### Steps to reproduce

I'm using Micromark in an astro project, and ever since installing micromark 3.0.8 I get this error:

```
[15:04:05] [snowpack] + classnames@2.3.1
[build] Unable to render src/pages/renew/checkout.astro

ReferenceError: document is not defined
```

While this might be snowpack being finnicky, micromark@3.0.7 works totally fine! So just wondering if anything has been introduced which could cause it.

### Expected behavior

My project builds:

### Actual behavior

```
[15:04:05] [snowpack] + classnames@2.3.1
[build] Unable to render src/pages/renew/checkout.astro

ReferenceError: document is not defined
```

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Snowpack

**Comment by wooorm** [comment]
Didn’t they switch to Vite? How are you using micromark? What are they using to bundle?

**Comment by ChristianMurphy** [comment]
Astro 0.21 moved to vite https://astro.build/blog/astro-021-release/ (released 4 days ago https://github.com/snowpackjs/astro/releases/tag/astro%400.21.0)
@radiosilence it may be worth giving the latest version of astro a try. (That said, both snowpack and vite are rollup based, upgrading is not a guaranteed fix, still worth a try)

I'd also second the question:

> How are you using micromark?

understanding where an how micromark is being called is important for tracing the potential issue.
A runnable example would be really helpful for this https://astro.new/ provides some starters.

**Comment by radiosilence** [comment]
We're upgrading to 0.21 as we speak, but I figured this change might be something to look into anyway :)

We're calling it like this:

```tsx
import { micromark } from 'micromark';
import { HTMLAttributes } from 'react';

export interface MarkdownProps extends HTMLAttributes<HTMLDivElement> {
  children: string;
}

export function Markdown({ children, className = '', ...rest }: MarkdownProps) {
  return (
    <div
      dangerouslySetInnerHTML={{ __html: `${micromark(children)}` }}
      className={`prose max-w-full ${className}`}
      {...rest}
    />
  );
}

```

**Comment by wooorm** [comment]
This is likely an astro/snowpack/rollup bug.
The difference is that we used to have a `browser` field to load browser code (https://github.com/wooorm/parse-entities/commit/cd47ffd1a32d3ca398ba768ff89b41400a1c98c9#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) and now it’s a `browser` condition (https://github.com/wooorm/decode-named-character-reference/blob/65da0f9dbee48aea74665255456d4e95d1f5cbc1/package.json#L36).
For some reason the tooling in astro/snowpack/rollup was not picking the `browser` field on servers but *is* picking the browser condition 🤷‍♂️

**Comment by wooorm** [comment]
Someone reproduced this exact error with just skypack: https://github.com/remarkjs/remark/discussions/909. So it seems definite that it’s an error there. Probably good to raise it with them!

**Comment by theprojectsomething** [comment]
I'm getting this same issue bundling with Vite (for a worker). The default include seems to rely on the dom for character decoding, though doesn't seem to effect things when running directly from node. Issue disappears when downgrading to 2.11.4

**Comment by wooorm** [comment]
That’s Vite’s choice: to default to telling everyone that they are running in a browser:

https://github.com/wooorm/decode-named-character-reference/blob/ddb8cdf65a7ce4795c4fc45c8433495377b0f5ea/package.json#L33-L39

Perhaps you can configure Vite to not choose browser versions if you are not in a browser, instead of downgrading dependencies?

**Comment by theprojectsomething** [comment]
Interesting, thanks for the pointer @wooorm .. I did spend a bit of time messing with random Vite config settings with no luck (specifically, I tried changing the build target and setting SSR mode). Let me follow up with Vite. Thanks.
