### ISSUE TITLE
`index.d.ts` is missing in `micromark-util-encode` published files

### ISSUE THREAD

**Issue by jaydenseric** [micromark/micromark#107]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-util-encode@1.0.0

### Steps to reproduce

The `package.json` published for `micromark-util-encode` v1.0.0 contains `"types": "index.d.ts"`:

https://unpkg.com/browse/micromark-util-encode@1.0.0/package.json

Yet the `index.d.ts` file is not in the `files` whitelist:

https://github.com/micromark/micromark/blob/efe9c4d7b7607a35dbc264a6f29904c532277b2b/packages/micromark-util-encode/package.json#L33-L35

Most likely that is the reason `index.d.ts` isn't published:

https://unpkg.com/browse/micromark-util-encode@1.0.0/

I haven't checked if other micromark packages have a similar issue, this is just what I discovered in my particular project:
<img width="1030" alt="Screen Shot 2021-12-25 at 10 41 32 am" src="https://user-images.githubusercontent.com/1754873/147374339-a45051e8-f7dd-4b7e-8f6d-c49b7a3e7aa0.png">

### Expected behavior

Types declared in the `package.json` should be published.

### Actual behavior

Types declared in the `package.json` are not published.

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
I looked through all `"files"` fields and it’s not missing in other places

**Comment by wooorm** [comment]
Fixed in https://github.com/micromark/micromark/commit/0e7aae7d0e93f0aa48949d314913fc99fa516b72

**Comment by wooorm** [comment]
…and released!
