### ISSUE TITLE
HTML with excess whitespace is not parsed correctly

### ISSUE THREAD

**Issue by bryanph** [micromark/micromark#109]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark 3.0.10, mdast-util-from-markdown 1.2.0

### Link to runnable example

https://codesandbox.io/s/awesome-elbakyan-c0gus?file=/src/index.ts

### Steps to reproduce

If you remove the line between `Some HTML` and `Spanning multiple lines` it does work but excess whitespace makes the parser confused (it thinks the extra line means a new paragraph starts)

### Expected behavior

The HTML should be all combined in a single `html` node

### Actual behavior

The parsing fails

**Comment by wooorm** [comment]
“Fails”?

If you mean that `Spanning multiple lines` turns into a paragraph, that is how markdown (CommonMark, GFM, markdown.pl) works. That’s expected.

**Comment by bryanph** [comment]
You're right, my bad
