### ISSUE TITLE
hard break at the end of a paragraph is not properly parsed

### ISSUE THREAD

**Issue by tripodsan** [micromark/micromark#118]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micormark

### Link to runnable example

https://codesandbox.io/s/thirsty-fire-1jdcgn

### Steps to reproduce

parse this:

```markdown
# Trailing hard-break

This break is properly detected\
yes?

But a trailing break is not\



What's worse, it leaves a stray `\`
```

checking the github behaviour, it's the same :-( but of course this is rather unfortunate and is difficult to find a workaround.

### Expected behavior

```html
<h1>Trailing hard-break</h1>
<p>This break is properly detected<br />
yes?</p>
<p>But a trailing break is not<br /></p>
<p>What's worse, it leaves a stray <code>\</code></p>
```

### Actual behavior

```html
<h1>Trailing hard-break</h1>
<p>This break is properly detected<br />
yes?</p>
<p>But a trailing break is not\</p>
<p>What's worse, it leaves a stray <code>\</code></p>
```

### Runtime

Node v14

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
That’s how markdown works: CommonMark, and as you found out, GFM.
The original markdown, and basically all markdown parsers, work [the same](https://babelmark.github.io/?text=But+a+trailing+break+is+not%5C%0A).
It stems from HTML also seeing it as invalid: hard breaks are semantic breaks in prose. Not breaks at ends of paragraphs.
Given that this project follows CommonMark, this is not an issue in this project.

**Comment by tripodsan** [comment]
ok. fair enough.
