### ISSUE TITLE
Make `definitions` available to extensions

### ISSUE THREAD

**Issue by tripodsan** [micromark/micromark#121]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

i'm writing an extension where I would need the [definitions](https://github.com/micromark/micromark/blob/27d3426f0181215a60700424c36671467592e495/packages/micromark/dev/lib/compile.js#L84) defined in the document. 

### Solution

the definitions should be available either via the context `this.definitions` or via `getData('mediaDefinitions')`.
the latter is probably better.

### Alternatives

I could probably overwrite all the definition related enter and exit methods, and track them as well, but this sounds like a wrong approach.

**Comment by wooorm** [comment]
Feel free to create a PR that exposes it, just like 'tightStack'?
