### ISSUE TITLE
Custom extensions break in development mode, despite working in production

### ISSUE THREAD

**Issue by chudoklates** [micromark/micromark#125]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.1.0

### Link to runnable example

https://github.com/chudoklates/micromark-error-demo

### Steps to reproduce

Use repo provided above.

Generally, for this error to occur, the parser needs to be run through Webpack in `development` mode. There also needs to be an extension which calls `effects.consume()` in its syntax before `effects.enter()` is called

### Expected behavior

Actions which are permissible in the production distribution should also be permissible in development mode.

### Actual behavior

A TypeError is thrown when the code reaches this assertion:

```js
// at the point of error: code: 123, context.events: []
assert(
      code === null
        ? context.events.length === 0 ||
            context.events[context.events.length - 1][0] === 'exit'
        : context.events[context.events.length - 1][0] === 'enter',
      'expected last token to be open'
    )
```

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.consume (create-tokenizer.js:246:52)
    at onStart (extensions.js:45:13)
    at start (create-tokenizer.js:460:12)
    at start (create-tokenizer.js:401:46)
    at start (text.js:49:30)
    at go (create-tokenizer.js:229:13)
    at main (create-tokenizer.js:209:11)
    at Object.write (create-tokenizer.js:135:5)
    at subcontent (index.js:198:17)
    at subtokenize (index.js:90:30)
```

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Your extension is wrong. The solution is: don’t create broken extensions.
The reason this throws in development, is that in development, there are extra safe guards to help you not write broken extensions.
In production, it is assumed that your extensions are valid.

**Comment by chudoklates** [comment]
> Your extension is wrong. The solution is: don’t create broken extensions. The reason this throws in development, is that in development, there are extra safe guards to help you not write broken extensions. In production, it is assumed that your extensions are valid.

sooo... when assumed valid, it works, but it's broken?

**Comment by wooorm** [comment]
Yes. You assume it is valid but it is not, it’s broken. You can only consume in (void) events.

**Comment by chudoklates** [comment]
Is there anyplace I can read on more detailed implementations of micromark extensions (beyond what's there in the readme)? I basically would have to refactor an existing implementation that was already running in production, and have nowhere near the knowledge to reimplement it in a correct way
