### ISSUE TITLE
Configure collapsing newlines into a single paragraph

### ISSUE THREAD

**Issue by Kycermann** [micromark/micromark#130]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want to have several paragraphs like this:

```md
I am a paragraph.
I am part of the same paragraph.

But I am a new paragraph.
```

This is compiled to the following:

```md
I am a paragraph. I am part of the same paragraph. But I am a new paragraph.
```

### Solution

I'd expect the following result:

```md
I am a paragraph. I am part of the same paragraph.

But I am a new paragraph.
```

### Alternatives

I could use the `<p>` tag manually in the Markdown.

**Comment by Murderlon** [comment]
When I use AST explorer with `remark`, which uses `micromark` under the hood, I can see it correctly has two paragraphs:

https://astexplorer.net/#/gist/9bd6648bede8ec2cbde59569f81584fc/latest

Creating a reproducible example on codesandbox or stackblitz would help.
