### ISSUE TITLE
Reduce execution time by ~11% with a simple reimplementation of TokenizeContext.now

### ISSUE THREAD

**Issue by DavidAnson** [micromark/micromark#139]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest main branch

### Steps to reproduce

I ran a profile of `micromark` and noticed `TokenizeContext.now` was something like the 4th most time-consuming function. It’s quite a simple function as all it does is return a copy of `point`. I tried a couple of alternate implementations and found one that reduces runtime by ~11% on an Apple Silicon M1 (mac Mini). I imagine the delta is different on other hardware, so maybe other folks can give this a try on their hardware? That said, I expect this change will be more efficient everywhere because it avoids a call into `Object.assign` and tells the JIT exactly what needs to be done. All tests pass with this change; you can see the code change and minimal test harness here: <https://github.com/micromark/micromark/compare/main...DavidAnson:micromark:TokenizeContext-now>.

I added a scenario to `perf.js` that reads the content of `readme.md` and calls `micromark` 500 times. This input seems fairly representative, but I’m happy if folks want to profile on something else. The numbers below are pretty stable, so I only took three samples before/after.

The 3 readings I did before changing anything: ((17.726 + 17.786 + 17.606) / 3) = 17.706s

The 3 readings I did after making the change: ((15.75 + 15.676 + 15.688) / 3) = 15.705s

By my math, the time eliminated is: ((17.706 - 15.705) / 17.706) = 0.1130 = 11.30%

To be sure, the alternate implementation I propose here violates the encapsulation of `Point` - but a simple test case could be added to ensure any future changes to `Point` are accomodated.

I can send a proper PR if folks are open to this change.

### Expected behavior

N/A

### Actual behavior

N/A

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
Really appreciate you digging in performance!

It’s a very hot path, so I can definitely imagine that this is faster. I don’t worry about more fields being added in the future, TypeScript will catch that, and then we can solve it here.

I’d accept a PR for this!
a) Can you add a comment above the line, something along the lines of:
```
// This is a hot path, so we do this manually instead of `Object.assign({})`:
```
b) having a perf test of 500x the readme is a good idea, but I think the `fs.readFile` call should be outside the speed check, and it would be nice to have the original checks still there!

**Comment by DavidAnson** [comment]
Great, I'll send something soon!

To clarify:

1. The `readFile` call is not being measured. But I will move it to the top of the file per your comment.
2. You may not have noticed that I am not using `ms` to output the timing measurement. I wanted millisecond precision instead of the simplified version used elsewhere.
3. I noticed later that the internals of `Point` are accessed elsewhere in this file already, so this is not groundbreaking.

**Comment by DavidAnson** [comment]
PR is here: https://github.com/micromark/micromark/pull/140

I increased the iteration count to 1000 and standardized the timing display to match the existing tests.
