### ISSUE TITLE
`micromark-util-symbol` can not be imported by typescript

### ISSUE THREAD

**Issue by ylc395** [micromark/micromark#153]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-util-symbol@2.0.0

### Steps to reproduce

try to import `micromark-util-symbol` in typescript

### Expected behavior

no type error reporting

### Actual behavior

get error: Cannot find module 'micromark-util-symbol' or its corresponding type declarations.ts(2307)

### Possible Solution

add a field in package.json:

```
  "types": "./lib/default.d.ts",
```

**Comment by wooorm** [comment]
That should not be a problem. `exports` points to `./lib/default.js`, which exists. Also a `lib/default.d.ts` exists. https://www.npmjs.com/package/micromark-util-symbol?activeTab=code

We use this project in tons of places already. It’s type checked everywhere. Perhaps you misconfigured TypeScript?

**Comment by remcohaszing** [comment]
You should set `moduleResolution` to `node16`, `nodenext`, or `bundler`.

This project could be updated to work with the legacy `node10` (aka `node`) option, but really people should no longer use that.

**Comment by ylc395** [comment]
That's fine. I add a new file `vendor.d.ts`

```ts
declare module 'micromark-util-symbol' {
  export * from 'micromark-util-symbol/lib/default';
}
```

to suppress this error and keeping legacy tsconfig unchanged.

**Comment by wooorm** [comment]
Why would you not want to use a modern tsconfig? 🤔

**Comment by ylc395** [comment]
Many other libraries are not esm module, so I have to run everything in commonJS mode. Could you share me some advices? @wooorm

**Comment by wooorm** [comment]
How to get ESM working in Electron seems like a different problem? It should be possible to use a modern tsconfig, and esm, and bundle as CJS to use in Electron?

**Comment by remcohaszing** [comment]
If you use a bundler, you should use:

```jsonc
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "bundler"
  }
}
```
