### ISSUE TITLE
Strings ending with `\n-` are compiled into a level 2 heading

### ISSUE THREAD

**Issue by stanwangsyd** [micromark/micromark#155]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.0

### Link to runnable example

https://codesandbox.io/s/trusting-star-wv879z?file=/src/index.mjs

### Steps to reproduce

I've created a minimal reproduction of the issue [here](https://codesandbox.io/s/trusting-star-wv879z?file=/src/index.mjs):

![Screenshot 2023-10-03 at 2 52 12 pm](https://github.com/micromark/micromark/assets/58194223/77cec59e-1ddc-4298-97e6-8690b6087eb5)

### Expected behavior

I'd expect the string to be compiled into a paragraph with the hyphen to be at the start of the 2nd line.

### Actual behavior

The string is compiled into a level 2 heading

**Comment by ChristianMurphy** [comment]
Welcome @stanwangsyd! 👋 
That isn't a bug, it's called a Setext heading and it is a standard part of markdown. https://spec.commonmark.org/0.30/#setext-headings

**Comment by stanwangsyd** [comment]
Ah good to know, thanks for pointing me the doc 👍
