### ISSUE TITLE
Error - [webpack] 'dist': ./node_modules/micromark-util-decode-numeric-character-reference/index.js 23:11 Module parse failed: Identifier directly after number

### ISSUE THREAD

**Issue by Hasni501** [micromark/micromark#161]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

using node 18.17.1

### Steps to reproduce

I am using **botframework-webchat** and when i try to build it, the below error message pop-ups.

Error - [webpack] 'dist':
./node_modules/micromark-util-decode-numeric-character-reference/index.js 23:11
Module parse failed: Identifier directly after number (23:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   code > 126 && code < 160 ||
|   // Lone high surrogates and low surrogates.
>   code > 55_295 && code < 57_344 ||
|   // Noncharacters.
|   code > 64_975 && code < 65_008 || /* eslint-disable no-bitwise */
 @ ./node_modules/mdast-util-from-markdown/lib/index.js 138:0-97 1061:14-45
 @ ./node_modules/mdast-util-from-markdown/index.js
 @ ./node_modules/botframework-webchat/lib/markdown/private/iterateLinkDefinitions.js
 @ ./node_modules/botframework-webchat/lib/markdown/renderMarkdown.js
 @ ./node_modules/botframework-webchat/lib/index.js
 @ ./lib/extensions/chatbotExtension/renderer/Chatbot.js
 @ ./lib/extensions/chatbotExtension/renderer/ChatbotPanel.js
 @ ./lib/extensions/chatbotExtension/ChatbotExtensionApplicationCustomizer.js
./node_modules/micromark-util-sanitize-uri/index.js 86:22

### Expected behavior

the package should build sucessfully

### Actual behavior

currently its giving error while running npm build

### Runtime

Node v16

### Package manager

npm v7

### OS

Windows

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
use modern webpack / use babel to compile modern code to work in very old javascript engines

**Comment by Hasni501** [comment]
> Which `webpack` version are you using? And, please, provide an online runnable reproduction.

webpack-cli ^5.1.4

**Comment by JounQin** [comment]
Again, an online runnable reproduction is required.

**Comment by Hasni501** [comment]
https://github.com/Hasnii501/app-extension.git

**Comment by Hasni501** [comment]
> Again, an online runnable reproduction is required.

https://github.com/Hasnii501/app-extension.git

**Comment by JounQin** [comment]
@Hasni501 You're still using `webpack@4` in the reproduction repository.

**Comment by Hasni501** [comment]
> @Hasni501 You're still using `webpack@4` in the reproduction repository.

Im a newbie, am sorry, but I am unable to understand this, can you please the steps to fix it?

**Comment by wooorm** [comment]
There are a ton of resources about webpack and other tools on the internet. You can do some research and try some tinkering yourself. That's how you learn ;)

**Comment by Hasni501** [comment]
> > use modern webpack / use babel to compile modern code to work in old javascript engines.
> > We support modern code/Node, as mentioned in the readme

I am using SharePoint Online SPFX framework, its not native react application.

**Comment by ChristianMurphy** [comment]
@Hasni501 adding on a bit.
It is an issue in the build tool, and is very specific to SharePoint rather than micromark.
SharePoint has their own support forum at https://sharepoint.stackexchange.com/search?q=webpack which has a number of related issues which may help you track down the issue.
