### ISSUE TITLE
Implementation of autolink and literalAutolink (micromark-extension-gfm-autolink-literal) are inconsistent when handling "@."

### ISSUE THREAD

**Issue by DavidAnson** [micromark/micromark#164]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark 4.0.0, micromark-extension-gfm-autolink-literal 2.0.0

### Steps to reproduce

```markdown
user@.com

<user@.com>

<user@e.com>
```

### Expected behavior

Consistent treatment of `user@.com` by autolink and literalAutolink.

### Actual behavior

`user@.com` and `<user@.com>` are both emitted as literalAutolink. Expected behavior is observed for `<user@e.com>` which is emitted as autolink.

This is significant for a linter which can be confused by the current behavior into adding infinite `<>` wrappers attempting to turn `user@.com` from literalAutolink into autolink: https://github.com/DavidAnson/markdownlint/issues/1140

I propose that `<user@.com>` should be treated as autolink, which is seemingly possible if `emailAtSignOrDot` behaved differently: https://github.com/micromark/micromark/blob/8b08d16891f4d6801eb0c0e990bd7b87836c0826/packages/micromark-core-commonmark/dev/lib/autolink.js#L203-L205

The micromark tokens (when using  micromark-extension-gfm-autolink-literal) for parsing the above Markdown are:

```
content user@.com
  paragraph user@.com
    literalAutolink user@.com
      literalAutolinkEmail user@.com
lineEnding \n
lineEndingBlank \n
content <user@.com>
  paragraph <user@.com>
    data <
    literalAutolink user@.com
      literalAutolinkEmail user@.com
    data >
lineEnding \n
lineEndingBlank \n
content <user@e.com>
  paragraph <user@e.com>
    autolink <user@e.com>
      autolinkMarker <
      autolinkEmail user@e.com
      autolinkMarker >
lineEnding \n
```

### Runtime

Node v16

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment]
Welcome @DavidAnson! 👋 
The auto link implementation matches that of GitHub, which has the same behavior.
It is working as expected.

Example

---


user@.com

<user@.com>

<user@e.com>

**Comment by DavidAnson** [comment]
I would not say this behavior is "expected" (or even logical), but I see how it is bug-compatible and understand why that is important. :) Thanks for the quick response!

**Comment by ChristianMurphy** [comment]
GitHub uses a different heuristic for urls than commonmark.
There are edge cases sure, and that is something you could raise with the GitHub flavored markdown team.

The goal of the micromark project(s) is the match the specification.

---

Related:

Titus has been good at improving the commonmark spec.
The process to contribute back to GFM is a bit more opaque, and involves opening a support ticket and hoping it makes its way to the platform team.

**Comment by DavidAnson** [comment]
Rock and a hard place, I get it! I've worked around this inconsistency in markdownlint and will say there are remarkably few times I've had to subvert the micromark parser. So thank you!!

**Comment by wooorm** [comment]
I would really recommend to stick with GH. Folks will want their markdown to work with many tools. GH is soo big, and us (and you?) following that exactly, I think improves the world a bit! :)

**Comment by DavidAnson** [comment]
Missing context on what the underlying lint rule is trying to enforce: https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md

**Comment by wooorm** [comment]
Right, makes sense!
Personally, I would probably recommend if possible `<>` autolinks and otherwise full `[]()` links.
Then you can always recommend not using these “bare” GFM URLs.
Whether `<>` works is not too difficult to check in CM.

In the formatter we use the check is like this:

https://github.com/syntax-tree/mdast-util-to-markdown/blob/fd6a508cc619b862f75b762dcf876c6b8315d330/lib/util/format-link-as-autolink.js#L16-L33

The code looks a bit wobbly but haven’t had issues about it!

**Comment by DavidAnson** [comment]
You just described a newer rule, MD054/link-image-style: https://github.com/DavidAnson/markdownlint/blob/main/doc/md054.md

:)
