### ISSUE TITLE
Including license in NPM packages

### ISSUE THREAD

**Issue by paulbarmstrong** [micromark/micromark#167]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

While scanning my dependencies I found that micromark NPM packages don't include their actual license file. I believe it would make sense for the micromark NPM packages to include the license since the MIT license requires that it be included in all copies or substantial portions of the Software.

### Solution

Since there's 22 NPM packages in the repo and they would presumably all use the same license from the root repo directory, I propose adding a release script that copies the license file from the root repo directory into each of the package directories, like [this from vue router](https://github.com/vuejs/router/blob/main/scripts/release.mjs#L198-L201). I think it would then make sense to allow git to ignore license files in the package directories (but still allow NPM to include them).

### Alternatives

It could also be solved by copy-pasting the license into each of the package directories. I think that may not be preferrable due to causing duplicative content in the repo.

**Comment by remcohaszing** [comment]
I say we go for the alternative here.

- It saves a build step.
- The license doesn’t change anyway. Duplicating it isn’t a maintenance burden.
- Different packages in a monorepo could have different licenses, i.e. with different years or copyright holders.
- Other monorepos in the unified ecosystem do this as well.

**Comment by wooorm** [comment]
> I believe it would make sense for the micromark NPM packages to include the license since the MIT license requires that it be included in all copies or substantial portions of the Software.

IANAL but AFAIK this hasn’t been fought out in a court, but first of all, everything has copyright by default. The license then gives you some rights. I’d assume that a judge will not assume the word `MIT` in a package.json or on the npm website will give people more lenient permissions than a whole copy of the license.

So, I’d wager, the code is MIT with or without that file existing in your `node_modules` folder.

I don’t really mind copying the files everywhere though. I’d also want to drop the copyright years. More projects are doing that.

**Comment by paulbarmstrong** [comment]
Thanks. Here's a PR for dropping the year from the copyright and copying the file into all the NPM package directories: https://github.com/micromark/micromark/pull/168
