### ISSUE TITLE
Performance: larger MDX files are unmanagably slow to parse

### ISSUE THREAD

**Issue by robsimmons** [micromark/micromark#169]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-from-markdown 2.0.0, micromark-extension-mdjs 3.0.0

### Link to runnable example

[Link to code and sandbox](https://codesandbox.io/p/devbox/hq4gqw?migrateFrom=58zrzp&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu8w30t500062e66dkucaq3v%2522%252C%2522sizes%2522%253A%255B49.282407407407405%252C50.717592592592595%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu8w30t500022e66g5x1qwko%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu8w30t500042e667tb2q5lb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu8w30t500052e66ihox4m04%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu8w30t500022e66g5x1qwko%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu8w30t500012e66qzjvct7a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clu8w30t500022e66g5x1qwko%2522%252C%2522activeTabId%2522%253A%2522clu8w30t500012e66qzjvct7a%2522%257D%252C%2522clu8w30t500052e66ihox4m04%2522%253A%257B%2522id%2522%253A%2522clu8w30t500052e66ihox4m04%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu8w30t500042e667tb2q5lb%2522%253A%257B%2522id%2522%253A%2522clu8w30t500042e667tb2q5lb%2522%252C%2522activeTabId%2522%253A%2522clu8w38rj00852e66ul6f9va0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu8w30t500032e66elk8dv2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu8w3154000tdaf81h4x9an8%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clu8w38rj00852e66ul6f9va0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

Run the following code (node v20.10.0 / npm v10.2.3), which generates and parses progressively larger mdx files up to about 180k lines

```javascript
import { fromMarkdown } from "mdast-util-from-markdown";
import { mdxjs } from "micromark-extension-mdxjs";

/* Generate test data */
const NUM_LINES_IN_CODE_SEG = 10000;
function generateTestData(size) {
  let file = [];
  for (let i = 0; i < size; i++) {
    file.push("", "<DummyComponent code={`");
    for (let j = 0; j < NUM_LINES_IN_CODE_SEG; j++) {
      file.push(crypto.randomUUID());
    }
    file.push("`} />", "");
  }
  return file.join("\n");
}

/* Return the number of milliseconds need to parse a test case */
function testPerformance(size) {
  const file = generateTestData(size);
  const start = performance.now();
  fromMarkdown(file, { extensions: [mdxjs()] });
  const end = performance.now();
  return end - start;
}

for (let reps = 0; reps < 3; reps++) {
  for (let size = 3; size < 20; size = Math.floor(size * 1.35)) {
    console.log(`${size}, ${testPerformance(size)}`);
  }
}
```

### Expected behavior

Parser is able to handle these files - reported running times grow linearally

### Actual behavior

Parser is very slow, and reported running times suggest parsing time scales quadratically or worse with the input file size.

![log-log parse time (ms) vs  size(1)](https://github.com/micromark/micromark/assets/442315/52b3157a-2e85-4796-8fa2-5bce3c4dcec8)
![parse time (ms) vs  size(1)](https://github.com/micromark/micromark/assets/442315/ef9c17d2-0597-45f2-ad1a-70a39d85c276)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

macOS

**Comment by robsimmons** [comment]
I suspect this is related to #23 - the code spends almost 100% of its time in [this `while` loop](https://github.com/micromark/micromark/blob/723c9b7e14c9f8d805bf80479f846bf6bda9a91a/packages/micromark-util-subtokenize/dev/index.js#L245-L251).

While this is synthetic data, but I came across this issue through Astro, as the MDX-parsing step for twelf.org was taking 60 minutes due to a 500kb generated markdown file. We have a workaround for that, but even on much smaller files MDX parsing is the slowest part of the site building process.

**Comment by wooorm** [comment]
Why do you generate a 500kb markdown file, and call it `.mdx` instead of `.md` 🤔

**Comment by robsimmons** [comment]
It's actually MDX - the content is all in a `<DummyComponent />`. The MDX usage is probably a red herring for the performance issues, but the place where I was encountering 60-minute parse times came from a file that had the structure of >90% of the content being in large template strings passed to MDX components.

**Comment by robsimmons** [comment]
Just to close the loop, here are those two graphs again with a fresh npm install that grabs the updated subcomponent-2.0.1: 

![parse time (ms) vs  size(2)](https://github.com/micromark/micromark/assets/442315/648e02a5-3a42-4cd2-9ef6-291f8dd8994b)

![log-log parse time (ms) vs  size(2)](https://github.com/micromark/micromark/assets/442315/3f8a7cc3-6a89-4b9b-b864-88cd2343f627)
