### ISSUE TITLE
 codes.js is not exported from package node_modules/micromark-util-symbol

### ISSUE THREAD

**Issue by cloudcompute** [micromark/micromark#182]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

next-mdx-remote, version ^5.0.0

### Steps to reproduce

import serialize from next-mdx-remote 

use serialize

### Expected behavior

It should be able to serialize the mdx content

### Actual behavior

It raises this exception in 'next dev' mode: Package path ./codes.js is not exported from package /.../web/node_modules/micromark-util-symbol

[1]    automatically enabled Fast Refresh for 1 custom loader
[1]  ⨯ ../../node_modules/micromark-extension-mdx-expression/node_modules/micromark-util-character/dev/index.js:5:1
[1] Module not found: Package path ./codes.js is not exported from package /.../web/node_modules/micromark-util-symbol (see exports field in /.../web/node_modules/micromark-util-symbol/package.json)
[1] 
[1] https://nextjs.org/docs/messages/module-not-found
[1] 
[1] Import trace for requested module:
[1] ../../node_modules/micromark-extension-mdx-expression/dev/lib/syntax.js
[1] ../../node_modules/micromark-extension-mdx-expression/dev/index.js
[1] ../../node_modules/micromark-extension-mdxjs/index.js

### Package manager

pnpm

### OS

Linux

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Solve your tools or raise with Next.js. This project needs no change.

**Comment by ChristianMurphy** [comment]
Welcome @cloudcompute!
There isn't a bug here, codes.js isn't imported by the character package
https://github.com/micromark/micromark/blob/08df4bcc15b2ad01cb297951f298c872ccdd4d35/packages/micromark-util-classify-character/dev/index.js#L1-L38

Most likely you have an outdated version of next-mdx-remote, micromark, or next.
Please update your packages!

**Comment by cloudcompute** [comment]
@ChristianMurphy Thank you for the quick response.

No control over micromark, using next-mdx-remote's latest version, and next's 14.2.7

If you have any idea If uppgrading next to 15, will help solve, let me know. Thanks again.

**Comment by cloudcompute** [comment]
Downgraded to 4.4.1 aand it worked. So the cause of error is in the latest version.

**Comment by ChristianMurphy** [comment]
@cloudcompute no, the bug is still in Next.js
The older version may not trigger the Next.js + configuration bug, that doesn't mean we need to risk breaking everyone else to work around that.

**Comment by cloudcompute** [comment]
Okay got it. I am using next 14.2 and next-mdx-remote 4.4.1 right now. 

But the combination of next 14.2 and next-mdx-remote 5.0 gives the error.

Will try to upgrade both next 15 and next-mdx-remote 5.0 and see whether it works.

Thanks
