### ISSUE TITLE
Support configuring `__xxx__` to generate <u>xxx</u> instead of <strong>xxx</strong>.

### ISSUE THREAD

**Issue by i18nsite** [micromark/micromark#183]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want have a config let `__xxx__` to generate `<u>xxx</u>`  instead of `<strong>xxx</strong>`

So that I can configure the display style to be underlined rather than bold

**Comment by wooorm** [comment]
Hi. That’s not how markdown works — so that’s outside of the scope of this project

**Comment by wooorm** [comment]
Sounds like you want to use CSS.

**Comment by i18nsite** [comment]
> Sounds like you want to use CSS.

Yes, but i need `__xxx__` generate different html tag than `**xxx**`

**Comment by i18nsite** [comment]
> Hi. That’s not how markdown works — so that’s outside of the scope of this project

@wooorm 

If I want to create a fork that supports this feature, what code should I modify? 

I cloned the source code, but did not find the part that generates strong html tags.

Thank you.

**Comment by wooorm** [comment]
a) use css...
b) I’d recommend, before forking things, to take some time with the readme. In this case, you will read that you can create extensions...
c) you checked a box sayin you read the support docs — then you also know discussions is a good place to ask questions. To get a good answer, we need to know your problem in-depth. a discussion is a good place for a discussion about things

**Comment by i18nsite** [comment]
I found that modifying the source code or writing a plug-in was too complicated. 
  
I came up with a simpler solution, which was to write a state machine for preprocessing. 
 
The screenshots of my implementation are as follows:
![CleanShot 2024-10-24 at 23 15 52](https://github.com/user-attachments/assets/b5c81a7c-b384-4927-99a1-f2a9b6c5c78f)

Package: https://www.npmjs.com/package/@3-/md__

Code
```js
export default (txt) => {
	const NORMAL = 0,
		INLINE_CODE = 1,
		CODE_BLOCK = 2;

	let state = NORMAL;
	let result = "";
	let underlineStart = -1;
	let pendingUnderline = "";

	for (let i = 0; i < txt.length; i++) {
		const char = txt[i];
		const isNewline = "\n\r".includes(char);

		switch (state) {
			case NORMAL:
				if (char === "`") {
					if (txt.startsWith("```", i)) {
						state = CODE_BLOCK;
						result += "```";
						i += 2;
					} else {
						state = INLINE_CODE;
						result += "`";
					}
				} else if (txt.startsWith("__", i)) {
					if (underlineStart === -1) {
						underlineStart = result.length;
						pendingUnderline = "__";
						i++;
					} else {
						result =
							result.slice(0, underlineStart) +
							"<u>" +
							result.slice(underlineStart) +
							"</u>";
						underlineStart = -1;
						pendingUnderline = "";
						i++;
					}
				} else {
					if (isNewline && underlineStart !== -1) {
						// 保留未闭合的下划线标记
						result =
							result.slice(0, underlineStart) +
							pendingUnderline +
							result.slice(underlineStart);
						underlineStart = -1;
						pendingUnderline = "";
					}
					result += char;
				}
				break;

			case INLINE_CODE:
				result += char;
				if (char === "`" || isNewline) {
					state = NORMAL;
				}
				break;

			case CODE_BLOCK:
				result += char;
				if (char === "`" && txt.startsWith("```", i - 2)) {
					state = NORMAL;
				}
				break;
		}
	}

	// 处理文本结束时未闭合的下划线标记
	if (underlineStart !== -1) {
		result =
			result.slice(0, underlineStart) +
			pendingUnderline +
			result.slice(underlineStart);
	}

	return result;
};
```

Test
```js
#!/usr/bin/env node

import { micromark } from "micromark"
import md__ from "@3-/md__"

const mdmark = (md, opt = {}) =>
	micromark(md__(md), { allowDangerousHtml: true, ...opt })

console.log(mdmark("Hello __world__ test"))
// Hello <u>world</u> test

console.log(mdmark("__<__ `__b__` __c__ ```__d__``` __not close"))
// <u>&lt;</u> `__b__` <u>c</u> ```__d__``` __not close

console.log(mdmark("__[link](http://example.com)__"))
// <u><a href="http://example.com">link</a></u>

console.log(mdmark("__a\nb__"))
// __a
// b__

console.log(mdmark("```\n__code__\n```"))
// ```
// __code__
// ```

const txt = "对__中文__加粗**更加**友好"

console.log("micromark :", micromark(txt))
console.log("mdmark", mdmark(txt))
```

output :

```
<p>Hello <u>world</u> test</p>
<p><u>&lt;</u> <code>__b__</code> <u>c</u> <code>__d__</code> __not close</p>
<p><u><a href="http://example.com">link</a></u></p>
<p><strong>a
b</strong></p>
<pre><code>__code__
</code></pre>
micromark : <p>对__中文__加粗<strong>更加</strong>友好</p>
mdmark <p>对<u>中文</u>加粗<strong>更加</strong>友好</p>
```

**Comment by wooorm** [comment]
Hm. I recommend that people use CSS:

```css
strong {
  font-weight: normal;
  text-decoration: underline
}
```

**Comment by i18nsite** [comment]
> Hm. I recommend that people use CSS:
> 
> ```css
> strong {
>   font-weight: normal;
>   text-decoration: underline
> }
> ```

I want `**xxx**` show bold , and `__xx__` show underline

**Comment by i18nsite** [comment]
@wooorm 

I updated [@3-/md__](https://www.npmjs.com/package/@3-/md__) and added optimizations for the strikethrough syntax.

The underline, strikethrough, and bold syntax have been optimized, and the mark can be effective without spaces before and after, making it easier to write documents in languages ​​that do not use spaces as separators, such as Chinese, Japanese, and Korean.

For example:

```js
const txt = "对__中文__**加粗**和~~删除线~~更加友好"
console.log("micromark :", micromark(txt))
console.log("mdmark", mdmark(txt))
```

```
micromark : <p>对__中文__<strong>加粗</strong>和~~删除线~~更加友好</p>
mdmark <p>对<u>中文</u><strong>加粗</strong>和<del>删除线</del>更加友好</p>
```

Here is a Chinese document (which can be translated into English using Google Translate) that explains the design flaws of the markdown bold syntax, which makes it very unfriendly to languages ​​such as Chinese, Japanese, and Korean that do not use spaces as separators

https://juejin.cn/post/7064565848421171213

I use this in my site : https://i18n.site/i18n.site/md/styl
![CleanShot 2024-10-25 at 00 08 19](https://github.com/user-attachments/assets/e3c084f5-b8c7-4159-b316-a0125536ec2e)

**Comment by wooorm** [comment]
I recommend for next time, to ask your questions up front. You until now never said you wanted to differentiate `__` from `**`...

This project is about markdown. That is not markdown. You can do what you want on your site of course. But this place is about markdown. I do not recommend what you do.
