### ISSUE TITLE
500 Maximum call stack size exceeded in micromark-util-subtokenize/lib/splice-buffer.js

### ISSUE THREAD

**Issue by tripodsan** [micromark/micromark#187]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-util-subtokenize@2.0.2

### Steps to reproduce

it's hard to reproduce outside of my framework and my micromark extension. but the problem seems the be, that at one point during parsing, the `slice(start, end)` is invoked which causes it to push 123'260 items on the list using the spread operator:

https://github.com/micromark/micromark/blob/dd1bbe0c80fe4c4d1e3ee7adeaff1d8e81e3818f/packages/micromark-util-subtokenize/dev/lib/splice-buffer.js#L121-L123

this fails with:

```
500 Maximum call stack size exceeded RangeError: Maximum call stack size exceeded
    at Array.push (<anonymous>)
```

when I change this to:

```
    return list.concat(this.right.slice(this.right.length - stop + this.left.length).reverse());
```

it works.

---

```
$ node --version
v20.17.0
```

### Expected behavior

it should not generated a RangeError.

### Actual behavior

it throws a RangeError

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
Hi! A repro would be important — things need to be tested. Otherwise it will appear again.

Perhaps there is a problem in your code, your extension or your framework?

**Comment by tripodsan** [comment]
> Hi! A repro would be important — things need to be tested. Otherwise it will appear again.

yes. I can try to create a reproducible test... I thought, maybe you have a hunch what it can be, and can create a test that causes a 120k slice?

**Comment by tripodsan** [comment]
I seems to work with micromark-util-subtokenize@2.0.1 but not with 2.0.2

**Comment by tripodsan** [comment]
@wooorm here's a failing test: https://github.com/adobe/micromark-extension-gridtables/actions/runs/11894066651/job/33140467995#step:5:35

**Comment by wooorm** [comment]
Changing the code here might be good.

Still, [a file like your file](https://github.com/adobe/micromark-extension-gridtables/blob/main/test/fixtures/gt-large.md?plain=1), should likely not generate 120k events. This sounds like a bug in the extension.

**Comment by tripodsan** [comment]
> hould likely not generate 120k events. This sounds like a bug in the extension.

might be...the syntax is tricky :-) but it worked until now :-)

**Comment by tripodsan** [comment]
> Still, [a file like your file](https://github.com/adobe/micromark-extension-gridtables/blob/main/test/fixtures/gt-large.md?plain=1),

no, the one that causes issues is [this one](https://github.com/adobe/micromark-extension-gridtables/blob/broken-slice/test/fixtures/large.md)

**Comment by wooorm** [comment]
I recommend narrowing your problem down. Try and remove some lines. See when the crash appears/disappears. From the start, from the end. Is it related to non-ascii? When the crash disappears, can you then add other lines, to make it appear again?

**Comment by tripodsan** [comment]
> I recommend narrowing your problem down. Try and remove some lines. See when the crash appears/disappears. From the start, from the end. Is it related to non-ascii? When the crash disappears, can you then add other lines, to make it appear again?

I tried already... it's just the size. I can remove text anywhere until it works. also, due to https://github.com/nodejs/node/issues/41163, i have different results on my machine than on the CI machine.

**Comment by wooorm** [comment]
Doesn’t that reasoning point to a test case? We could run a large file with something like `node --stack_size <very-small>`?

**Comment by tripodsan** [comment]
> Doesn’t that reasoning point to a test case? We could run a large file with something like `node --stack_size <very-small>`?

yes. but what is an acceptable stack size?
I guess using the spread operator is problematic for potentially large arrays?
https://github.com/nodejs/node/issues/16870

**Comment by tripodsan** [comment]
example, w/o my extension active:

```
import assert from 'assert';
import { micromark } from 'micromark';


  // create test example
  const snippet = `
### test

paragraph.

`;
  const md = snippet.repeat(10000);
  const expected = 'html';
  const actual = micromark(md);
  assert.strictEqual(actual.trim(), expected.trim());
```

```
node_modules/micromark-util-subtokenize/lib/splice-buffer.js:102
    list.push(...this.right.slice(this.right.length - stop + this.left.length).reverse());
         ^

RangeError: Maximum call stack size exceeded
    at SpliceBuffer.slice (node_modules/micromark-util-subtokenize/lib/splice-buffer.js:102:10)
    at subtokenize (node_modules/micromark-util-subtokenize/index.js:107:59)
    at postprocess (node_modules/micromark/lib/postprocess.js:14:11)
    at micromark (node_modules/micromark/index.js:59:27)
    at test.js:14:18
```

**Comment by tripodsan** [comment]
> Adobe can help sponsor that work

I'll look into it....
