### ISSUE TITLE
Performance improvement: linked lists for events

### ISSUE THREAD

**Issue by wooorm** [micromark/micromark#23]
### Subject of the feature

Given that on large markdown files we are dealing with tons (literally, 100k or so) of events, improving performance might be switching from arrays to linked event objects.

### Problem

Operations on big arrays can be slow, such as https://github.com/micromark/micromark/pull/21.
Switching to linked lists adds complexity (while removing it in certain other cases!), but will *probably/hopefully* improve perf.

### Alternatives

We’re already using really fast array methods. And everything is mutating already. Maybe linked lists won’t net a lot.

**Comment by 3y3** [comment]
Things about linked list
https://gist.github.com/3y3/cd4d9272a5a309502ae7c2bf961788d1

This improves speed x2-x3 on [this](https://github.com/wooorm/a-dump-of-markdown) benchmark, but slows down processing of small files in markdown-it [benchmark](https://github.com/markdown-it/markdown-it/tree/master/benchmark)

**Comment by wooorm** [comment]
Ah, cool! Thanks for checking and providing code :)
