### ISSUE TITLE
images without alt should not generate alt attribute with empty string

### ISSUE THREAD

**Issue by tripodsan** [micromark/micromark#32]
### Subject of the issue

see https://github.com/micromark/micromark/blob/63cf51445077f18145d35dd3c506859d6f8195ce/test/io/text/image.mjs#L152

I don't know if this is really a bad thing, but the new behaviour of micromark is to generate an empty string for the _alt_ attribute, where as the old remark-parser used to set the _alt_ property of the mdast node to `null`.

there is a slight distinction, such as an image with an empty alt text is considered a decorative image and should be ignored by a screen reader. if the alt attribute is missing, it will just read the `src` (not a brilliant behaviour, either :-)

https://www.w3.org/WAI/tutorials/images/decorative/

In any case, the new behaviour allows the author to specify decorative images in markdown by default, which wasn't possible before.

### Expected behavior

not sure. But for backward compatibility's sake: A markdown image w/o an alt text should not create an alt attribute in HTML (mdast node's property should be `null`)

**Comment by wooorm** [comment]
> I don't know if this is really a bad thing, but the new behaviour of micromark is to generate an empty string for the alt attribute, where as the old remark-parser used to set the alt property of the mdast node to null.

Correct, this was not in old remark. This was raised on twitter a bit ago to me: having the empty alt instead of no alt thus is also practical, for accessibility, and not just theoretical. And I checked: it’s commonmark compliant to use an empty alt attribute.

> not sure. But for backward compatibility's sake: A markdown image w/o an alt text should not create an alt attribute in HTML (mdast node's property should be null)

Following commonmark is more important to me than backwards compat.

---

See also about title: https://github.com/commonmark/commonmark.js/issues/192

**Comment by tripodsan** [comment]
thanks!

**Comment by wooorm** [comment]
Btw: I appreciate hearing about the things you’re running into. Some of these are intended, but don’t let that discourage your from posting more!
