### ISSUE TITLE
What would the usage, api surface and extension points look like?

### ISSUE THREAD

**Issue by zeusdeux** [micromark/micromark#5]
To get more clarity on where this fits in in the @unifiedjs ecosystem, could the assigned folks add some example usages of this library in this issue please?

Examples of how this would be used by @remarkjs and/or @unifiedjs would be helpful as they would clear up the following questions:

- what would the usage of this library look like?
- who are the potential consumers of it?
- would this cause a rewrite or changes in how [`remark-parse`](https://github.com/remarkjs/remark/tree/master/packages/remark-parse) is written?
- what should the api surface look like?
- what are potential extension points?
- does this impact `processor.use` from the @unifiedjs world?
- will this stream tokens or eat a file and spit out all the tokens at once? (assuming this is a lexer)

..and any other you folks can come up with.

The idea behind this is to discuss and land on a common understanding of this project's technical goals (e.g., is this a lexer? a parser? I've seen both words around here leading to some confusion), nail the api surface and identify potential extension points. This should help speed up dev, lead to some early "documentation" and prevent misalignment on the goals.

Thanks!

**Comment by fazouane-marouane** [comment]
As I understand it, micromark would be an alternative parser for @remarkjs. What's different is the streaming part of the parsing: we parse as new data comes in. Data may come from a network call, local file and data maybe extremely huge.

There are already parsers for xml that do this. Maybe that we can understand how they operate and use some of their ideas.
1. in js: https://www.npmjs.com/package/sax
2. in haskell https://github.com/dredozubov/sax-parser
3. as a dedicated programming language for writing xml transformation http://gallium.inria.fr/~frisch/xstream/

So technically, if we create a streaming parser for CommonMark, the glue to make it work with unified world would be very small and easy to write. It would be sad indeed to loose all the power of those 'unist-util-*'. However, if we do only this, we loose the purpose of micromark since the expected usage is not to operate on a complete AST like in @unifiedjs.

The main challenge IMO, would be to have the same kind of utilities work with a streaming parser, somehow.

**Comment by wooorm** [comment]
Thanks for the issue @zeusdeux!

As @fazouane-marouane mentions, it would be very nice to support streaming. It’s not a *must* per se, but it would be nice. And the challenge he sees is indeed applicable:

> The main challenge IMO, would be to have the same kind of utilities work with a streaming parser, somehow.

this! 👍

> Examples of how this would be used by @remarkjs and/or @unifiedjs would be helpful

I think micromark should be used internally by remark-parse, and remark-parse will use micromark (and other utilities) to create mdast. Other remark plugins cool hook into the micromark parser as well.
It would be very nice for other non-remark things to be able to use micromark directly as well.

> what would the usage of this library look like?

That depends. My [example.js in #1](https://github.com/micromark/micromark/blob/3b5db99af8e8a2dc9bb1e77bcb983c687a7d1d5a/example.js) shows a bit of that.

> who are the potential consumers of it?

remark, things like mdx, things that directly parse to something else (like HTML) and don’t need to be as pluggable as unified, and other markdown parsers (remarkable, markdown-it).

> would this cause a rewrite or changes in how remark-parse is written?

Yes, most of remark-parse could be dropped. Instead remark-parse would focus on wrapping things together: glue code. Not on “actual code”.

> what should the api surface look like?

Maybe an implementation of streams (`.write()`, `.end()`, `.pipe()`). And some things to make it pluggable.

> what are potential extension points?

We need an interface that makes extensions easy. I find remark-parse.Parser and markdown-it confusing: something that’s easier than those.

> does this impact processor.use from the @unifiedjs world?

It would be nice if micromark could support the current [`unified.Parser`](https://github.com/unifiedjs/unified#processorparser) interface.
Other remark plugins (like remark-breaks, remark-frontmatter), would add a thing to the underlying parser. So they’d depend on a lower level utility (`@micromark/github-message-break`, `@micromark/frontmatter`), and wrap those.

> will this stream tokens or eat a file and spit out all the tokens at once? (assuming this is a lexer)

It would be nice if micromark could spit out tokens. Something else could take those tokens and form them into a CST/AST.

> is this a lexer? a parser? I've seen both words around here leading to some confusion

In my implementation for ATX headings, I’ve not really defined tokens yet. And I guess it depends on those tokens what “this is”. We definitely need a new parser. And I think an underlying thing that emits tokens makes sense. If that‘s a lexer, so be it!

---

Alright, not too long. Does this help? Anything I can expand upon?

**Comment by zeusdeux** [comment]
Thanks for the clarification @wooorm and @fazouane-marouane.

I think we should settle on a definition of tokens that will be emitted by micromark. Given the current state of the code, it looks like they'll map to all the subsections in the [CommonMark Spec](https://spec.commonmark.org/) (e.g., Paragraphs, Code spans, Links, etc). This is fine and implies that when a plugin wants to extend this lexer, they'd have to take care of "parsing" whatever new syntax they want to support. For e.g., a plugin for generating a [shortcode](https://github.com/djm/remark-shortcodes) token would have to parse the structure a shortcode can have.

> Yes, most of remark-parse could be dropped. Instead remark-parse would focus on wrapping things together: glue code. Not on “actual code”.

I guess remark-parse would just implement the grammar implied by CommonMark. E.g,.

```
Document = Block | Inline | Epsilon
Block = LeafBlock Document | ContainerBlock Document
Inline = Link Document | Image Document | CodeSpan Document
....
```

> Maybe an implementation of streams (.write(), .end(), .pipe()). And some things to make it pluggable.

I'm in favour of the same. I'd even remove the rest and only keep `pipe` to begin with as it seems like micromark will most likely be first in the chain (and accepting raw text). This also helps with our goal of small size as less code = small bundle size.

For example: `micromark(text).pipe(remark-parse).pipe(process.stdout)`

> We need an interface that makes extensions easy. I find remark-parse.Parser and markdown-it confusing: something that’s easier than those.

Yeah, this part is interesting. The code right now is basically a finite state automaton. In its current shape it's hard to extend. Taking, again, shortcodes as an example — the shortcode plugin would basically be a collection of states and transitions which add tokens to the stream. The states exposed by the hypothetical shortcode plugin would have to plug into Paragraphs, ATX Headings, ListItems, etc as shortcodes can be found while generating those tokens. I don't have clear ideas on this yet and would love to start a discussion on this in another issue. 

I see the following topics for a follow up:

- discussion on the external api surface area with an emphasis on _pluggability_ (for consumers of tokens)
- discussion on the internal api surface area (to be consumed by plugins) for _extensibility_ (for adding more token types to the output stream)

Core assumption for both topics: micromark is a streaming lexer where tokens map to subsections in the CommonMark spec (`ATX Heading`, `Paragraph`, etc)

wdyt?

PS: apologies for the late reply. Was away on a long early vacation.

**Comment by wooorm** [comment]
Going to close this as I settled on an interface that makes HTML for now, and has the [tokens](https://github.com/micromark/micromark/blob/main/lib/constant/types.js) needed for mdast (and a cst), although actually implementing those will probably change some stuff again!

Thanks y’al for thinking with me about this!
