### ISSUE TITLE
Lack of document and types for turning off constructs

### ISSUE THREAD

**Issue by ocavue** [micromark/micromark#50]
### Subject of the issue

micromark doesn't accept [`{disable: {null: []}}`](https://github.com/micromark/micromark/commit/21fecde98dcf3529b88bbf8c9f6295cdf781b588) as an extension when using TypeScript.

### Your environment

*   **OS**: macOS 10.15
*   **Packages**: `mdast-util-from-markdown@0.8.5`, `micromark@2.11.4`
*   **Env**: node v14.16.0; yarn 1.22.10

### Steps to reproduce

please check https://github.com/issueset/micromark-disable-typescript-issue

### Expected behavior

No typescript error. And it's better to have some document in the README.md for this feature.

### Actual behavior

```
 Type '{ disable: { null: string[]; }; }' is not assignable to type 'SyntaxExtension[]'.
```

**Comment by ChristianMurphy** [comment]
Pull requests are welcome!

**Comment by ocavue** [comment]
This issue shouldn't be closed. The *document* is fixed but the *typescript typings* is still broken. 

A minimal reproduction:

```
$ git clone https://github.com/issueset/micromark-50
$ cd micromark-50
$ yarn install 
$ yarn run tsc ./index.ts
index.ts:4:18 - error TS2322: Type '{ disable: { null: string[]; }; }' is not assignable to type 'SyntaxExtension'.
  Object literal may only specify known properties, and 'disable' does not exist in type 'SyntaxExtension'.

4   extensions: [{ disable: { null: ["codeIndented"] } }],
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by ocavue** [comment]
BTW, I can't find any typescript file in the current `main` branch when I want to fix this issue. It seems that there is some kind of refactoring.

**Comment by ChristianMurphy** [comment]
@ocavue the typing are now generated from JSDoc

**Comment by ChristianMurphy** [comment]
Specifically here is the type for disable on extension
https://github.com/micromark/micromark/blob/116bfa56b90b6bbc1facddfd0886a7e127a6b03f/packages/micromark-util-types/index.js#L223

**Comment by ocavue** [comment]
That means this issue will be fixed when micromark v3 is released, right?

**Comment by ChristianMurphy** [comment]
Presumably

**Comment by ocavue** [comment]
Sounds good. Let's keep this issue closed then.
