### ISSUE TITLE
Please provide a helloworld on how to write an extension? The real ones are kind of complex...

### ISSUE THREAD

**Issue by justnewbee** [micromark/micromark#51]
### Subject of the feature

A helloworld is required on how to write an extension.

### Problem

The real extensions are too complex for quick reference.

### Expected behavior

A real simple extension.

### Alternatives

Say, I want to write an extension to make link external. Still digging around, maybe it is a good place for helloworld - modify attributes?

**Comment by wooorm** [comment]
> Say, I want to write an extension to make link external. Still digging around, maybe it is a good place for helloworld - modify attributes?

I’d strongly discourage extending markdown. Especially for this case. There are already directives, which at least has some potential of being semistandard. Otherwise, use mdast/remark/unified and use the AST

> The real extensions are too complex for quick reference.

Yes, they are. I don’t think they can ever be simple. micromark is relatively new, the internal APIs haven’t crystalised yet, I’ll add docs when that’s ready

**Comment by justnewbee** [comment]
> I’d strongly discourage extending markdown. Especially for this case. There are already directives, which at least has some potential of being semistandard. Otherwise, use mdast/remark/unified and use the AST

Em... your concern is right

However, it's our special need.

We're using markdown for documentation, and the content is to be displayed alongside our app. That's why we want to make the links inside the document external by default.

**Comment by wooorm** [comment]
I’m not against your end goal. I’m saying that the way you want to get there takes longer and is more complex than needed.

This is a much simpler solution https://unifiedjs.com/explore/package/remark-external-links/
