### ISSUE TITLE
Ordered lists starting with non-1 are not parsed when some content is present before them (micromark 3)

### ISSUE THREAD

**Issue by vadistic** [micromark/micromark#77]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.0 (via `mdast-util-from-markdown` 1.0.0)

Please let me know if this issue should be moved to `mdast-util-from-markdown`, but I think the bug is somewhere in micromark source :)

### Link to runnable example

https://codesandbox.io/s/naughty-ptolemy-y62bf?file=/src/index.ts

#### This is not parsed as list (paragraph before)

```
Content.

2. Hello
3. world
```

#### This is also not parsed as list (empty line before)

```

2. Hello
3. world
```

---

#### This is parsed as list (when trimmed, start number is correct)

```
2. Hello
3. world
```

#### This is also parsed as list (obviously)

```
Content 

1. Hello
2. world
```

### Expected behavior

List starting with non-1 numbers are parsed correctly.

Github handles it:

2. Hello
3. world

micromark pre-3 also handled it correctly.

### Actual behavior

List starting with non-1 numbers are not parsed correctly when  some paragraph or even empty line is present before them (in container?) 🤷 

```
Content.

2. Hello
3. world
```

```
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text",
                    "value": "Content.",
                    "position": {
                        "start": {
                            "line": 2,
                            "column": 1,
                            "offset": 1
                        },
                        "end": {
                            "line": 2,
                            "column": 9,
                            "offset": 9
                        }
                    }
                }
            ],
            "position": {
                "start": {
                    "line": 2,
                    "column": 1,
                    "offset": 1
                },
                "end": {
                    "line": 2,
                    "column": 9,
                    "offset": 9
                }
            }
        },
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text",
                    "value": "2. Hello\n3. world",
                    "position": {
                        "start": {
                            "line": 4,
                            "column": 1,
                            "offset": 11
                        },
                        "end": {
                            "line": 5,
                            "column": 9,
                            "offset": 28
                        }
                    }
                }
            ],
            "position": {
                "start": {
                    "line": 4,
                    "column": 1,
                    "offset": 11
                },
                "end": {
                    "line": 5,
                    "column": 9,
                    "offset": 28
                }
            }
        }
    ],
    "position": {
        "start": {
            "line": 1,
            "column": 1,
            "offset": 0
        },
        "end": {
            "line": 6,
            "column": 1,
            "offset": 29
        }
    }
}
```

### Runtime etc.

I do not think it's build / runtime dependent - it's some construct issue - but it happens both in browser & node - windows & linux.

**Comment by wooorm** [comment]
Great catch! Weird that that wasn’t tested. So many edge cases in markdown!

**Comment by wooorm** [comment]
Released!
