### ISSUE TITLE
How far to buffer?

### ISSUE THREAD

**Issue by wooorm** [micromark/micromark#8]
Markdown consists of blocks and inlines. Blocks are parsed per line.

Typically, at a certain point in a line, you know you’re right: take this ATX heading:

```markdown
###### A heading
```

When standing on the space, you know you’re in a heading: it can’t be anything else. So ATX headings don’t really need to buffer a lot: at most 6 characters.

Other values, need more, like this link definition:

```markdown
[take]:
https://this-link-definition
'asd
> block quote?
asd
asd
asd
asd
```

Only at the last character, the line feed without a closing title marker before it, do you know you need to backtrack, and parse the whole thing again. And it isn’t all a paragraph either, take for example the embedded `> block quote?`

An alternative example that needs to buffer infinity lines is indented code:

```markdown
␠␠␠␠this is a chunk (a properly indented non-blank line)
␠␠␠
␠␠
␠
␠␠
␠␠␠
␠␠␠␠
␠␠␠␠␠
␠␠␠␠
␠␠␠
␠␠
␠
␠␠␠
<-- And only here do we know the blank lines are not part of the indented code. Note that the line endings, and more that four spaces in a blank line, still show up in the code, so if we had another chunk, all the above line endings and that one extra space would be there.
```

🤔 So how far does one buffer? These are edge cases, not common in normal Markdown. But it could be interesting to see if we can cap this to reduce a potential memory problem.

**Comment by ChristianMurphy** [comment]
One possible answer:
We buffer until we can reliably determine which node type will be used.
For an example of GRL parser buffering see https://github.com/lezer-parser/lezer

**Comment by wooorm** [comment]
It seems to be possible to parse Markdown line-by-line, therefore one line would be the farthest one has to buffer.
A higher-level mechanism may have to “buffer” things though:
- For the indented code: blank line blocks are buffered when in an indented code block, and only output if there is a non-blank indented code line after them (and ignore if not)
- For definitions, I’m working on “MaybeDefinition” and “MaybeDefinitionTitle” blocks, which could be turned into “Paragraph”s if they can’t be valid, or “Definition”s if they are

**Comment by fazouane-marouane** [comment]
For indented code etc, could we stream the underlying data instead of buffering it or is there some gotchas?

**Comment by wooorm** [comment]
For indented code, it can already stream chunks of code, and blank lines (both as tokens), but to go to HTML you’d need to buffer continued blank lines and ignore them if they are not followed by more code chunks, and use them if they are!

**Comment by wooorm** [comment]
No need to buffer: we can instead queue tokens (at most a line), and later act on that queue. Specified in [CMSM: Overview](https://github.com/micromark/common-markup-state-machine#2-overview)
