### ISSUE TITLE
micromark handles links with custom protocol different from commonmark

### ISSUE THREAD

**Issue by ChristianMurphy** [micromark/micromark#90]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.5

### Link to runnable example

https://stackblitz.com/edit/node-qr2fly?file=index.js

### Steps to reproduce

```js
import { micromark } from "micromark";
import { Parser, HtmlRenderer } from "commonmark";

const reader = new Parser();
const writer = new HtmlRenderer();

const commonmark = (buf) => writer.render(reader.parse(buf));

const content = `<test:what>`;

console.log(micromark(content));
console.log(commonmark(content));
```

### Expected behavior

micromark and commonmark should produce the same HTML output

```html
<p><a href="test:what">test:what</a></p>
```

### Actual behavior

micromark produces different HTML

```html
<p><a href="">test:what</a></p>
```

### Runtime

Node v16

### Package manager

npm v7

### OS

Linux

**Comment by wooorm** [comment]
Isn't that the allowDangerousProtocol option?

**Comment by wooorm** [comment]
I’m pretty sure it’s that: https://github.com/micromark/micromark#optionsallowdangerousprotocol. micromark being safe by default, and optionally unsafe.
Let me know if I’m missing something!
