### ISSUE TITLE
Using power-assert causes Webpack builds to fail

### ISSUE THREAD

**Issue by Methuselah96** [micromark/micromark#95]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark@3.0.6

### Steps to reproduce

Use `micromark` in a Webpack app.

### Expected behavior

The app builds without configuration changes.

### Actual behavior

The build fails with:

```
WARNING in ../../node_modules/power-assert-formatter/lib/create.js 30:28-49
Critical dependency: the request of a dependency is an expression
 @ ../../node_modules/power-assert-formatter/index.js 12:0-40
 @ ../../node_modules/power-assert/index.js 15:16-49
 @ ../../node_modules/micromark/dev/lib/create-tokenizer.js 27:0-33 213:4-22 217:4-10 223:4-22 231:4-22 236:4-10 285:4-10 286:4-25 298:4-10 299:4-25 302:4-10 305:4-22 311:4-10 414:10-16 464:8-26 472:8-26 508:4-10 576:4-10 577:4-10 652:
10-16
 @ ../../node_modules/micromark/dev/lib/parse.js 14:0-53 49:13-28

```

and similar warnings for any package that now has a dependency on `power-assert`.

There is a solution provided by `power-assert` [here](https://github.com/power-assert-js/babel-plugin-espower/issues/14#issuecomment-197909419), but it seems like it would hide other warnings that I would want to see and I don't think I should need to modify my Webpack config to get `micromark` to work.

It would probably be better not to add `power-assert` as a dependency in a patch release since it's likely to break many people's builds.

Also note that the main `micromark` package uses `power-assert`, but I think it's missing from the the package's dependencies.

Out of curiosity, what is the advantage of switching to `power-assert`?

**Comment by wooorm** [comment]
The reason to use power-assert was that vite and webpack were not able to use assert: https://github.com/micromark/micromark/issues/87

**Comment by AviVahl** [comment]
Just noting our build started breaking too because of this issue.

**Comment by wooorm** [comment]
how did it work before?

**Comment by AviVahl** [comment]
Apparently, it previously picked up the actual [npm `assert` package](https://www.npmjs.com/package/assert), which "simply" worked. Our monorepo `package.json` explicitly installs this package, so it was always there.

**Comment by wooorm** [comment]
I’m thinking of either reversing the change and just documenting that folks need to configure their bundlers (by installing `assert`, by using https://github.com/unassert-js/rollup-plugin-unassert or https://github.com/unassert-js/webpack-unassert-loader, or by configuring their bundler to polyfill `assert`). Or, alternatively, to create a new `mini-assert` and get `unassert` to use it.

**Comment by AviVahl** [comment]
Since it's just simple assertions, that would be a really short function to implement. I'd even consider inlining it.
also, from a quick search in npm (searched for "tiny assert") there's https://www.npmjs.com/package/nanoassert

**Comment by wooorm** [comment]
One important addition is TypeScript.

> I'd even consider inlining it.

That prevents the assertions from being removed. micromark does not include assertions in production code. That would add assertions to production code.

**Comment by AviVahl** [comment]
I see. I don't think having it inline vs external package should affect the ability to disable / tree shake it in production mode. I'm not sure of micromark's current build process though, so I could be mistaken...

**Comment by Methuselah96** [comment]
I would be happy to create a types package with type assertions for any package that you would like to use.

**Comment by ChristianMurphy** [comment]
At least one assertion also does type narrowing in uvu https://github.com/lukeed/uvu/blob/d56753ec20928da1c22ff093cb07ce3c67613706/src/assert.d.ts#L4
But that and several other type fixes are unreleased, having happened after https://github.com/lukeed/uvu/releases/tag/v0.5.1

**Comment by wooorm** [comment]
Switched to `uvu/assert` everywhere!
