### ISSUE TITLE
ES5 Compatibility

### ISSUE THREAD

**Issue by justnewbee** [micromark/micromark#98]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

i moved from react-markdown to micromark for the reasons below:

1. react-markdown has a dependency that is es6 which breaks my app when it is run on IE11
2. react-markdown used to have a bug which micromark has no such issue
3. micromark is the 'smallest'

however, since version 1.x, the building target is es2020, there is a lot of `const`s, `let`s, method shortcuts and more which will definitely break my app...

### Solution

esm is a trend, and webpack can deal with it by default, however the es6 syntax... i may have to config my babel, and it might cost more time compliing.

so might it be possible to set build target to es5 which is for now the most compatible output? it does not hurt esm module.

part of my tsconfig.json

```
"target": "es5",
"lib": [
  "dom",
  "es2015",
  "es2017"
],
```

### Alternatives

no..

**Comment by justnewbee** [comment]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/2276086/139632512-aa81c527-55d2-4a87-bf58-0614fa0edd0d.png">

**Comment by justnewbee** [comment]
and the 0.x is OK

**Comment by wooorm** [comment]
ES5 is not a goal of this project, it isn’t going to be added.

You can use esbuild, swc, or indeed as you say configure Babel to compile modern code to code that works in IE11.

I like esbuild. Here’s how I create a modern module and a legacy nomodule version of code: https://github.com/wooorm/write-music/blob/ed0361cfc3e6b143f24b232430c71324f68676be/package.json#L34
Those two files are then used like so: https://github.com/wooorm/write-music/blob/ed0361cfc3e6b143f24b232430c71324f68676be/src/index.html#L18-L19.

**Comment by justnewbee** [comment]
sad...
it really isn't good...
es5 and esm does not conflict, all my packages are build into esm with target es5, it works well

u can see my package here https://www.npmjs.com/package/@alicloud/rc-markdown,
and the source code here https://github.com/aliyun/alibabacloud-console-base/tree/master/packages/rc-markdown

i really don't want whoever (including me) uses my package will have to change their build script.

**Comment by wooorm** [comment]
Writing code for packages published on npm in ES5 is not a good solution. It hurts all other users.
If package users want to support *deprecated*, 8 year old browser engines, then they can do so. With tools like esbuild, swc, or webpack/rollup. The rest of the ecosystem doesn’t need to suffer for that.
