### ISSUE TITLE
uvu shouldn't be set in dependencies

### ISSUE THREAD

**Issue by Ayc0** [micromark/micromark#99]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-core-commonmark@npm:1.0.4, micromark-extension-gfm-autolink-literal@npm:1.0.2, micromark-extension-gfm-footnote@npm:1.0.2, micromark-extension-gfm-strikethrough@npm:1.0.3, micromark-extension-gfm-table@npm:1.0.4, micromark-extension-gfm-task-list-item@npm:1.0.2

### Steps to reproduce

https://unpkg.com/micromark-core-commonmark@1.0.4/package.json and you can see that `uvu` is in the dependencies and not devDeps

### Expected behavior

uvu should be set in the dev deps so that, when installing any of the packages define here (like `micromark-core-commonmark`), `uvu` wouldn't be installed to (it's a test runner, not used in the runtime code)

### Actual behavior

`uvu` is listed in the deps so it get's installed

**Comment by wooorm** [comment]
Yep, it should. It’s a dependency. It’s referenced in the code that’s published and you can use: https://github.com/micromark/micromark#size--debug
